import intf_libs = lyrahgames-xstd%lib{lyrahgames-xstd}

./: lib{lyrahgames-pareto}: hxx{** -version} hxx{version} $intf_libs
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}
cxx.poptions =+ "-I$out_root" "-I$src_root"

hxx{version}: in{version} $src_root/manifest
{
  dist = true
  clean = ($src_root != $out_root)
}

hxx{**}:
{
  install = include/lyrahgames/pareto/
  install.subdirs = true
}
